name: dart_result
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  path: ^1.8.0
  json_annotation: ^4.6.0
  equatable: ^2.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.0.0
  json_serializable:
